"""Add BlacklistToken Model

Revision ID: da1a30ab85e6
Revises: 8609f245b67c
Create Date: 2021-06-14 13:36:32.678588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da1a30ab85e6"
down_revision = "8609f245b67c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
