# Github Workflow for Linting on Push and Push Request
name: "Flake8 Lint Check"

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: ["3.8", "3.9", "3.1"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install Dependencies
      run: |
        python install flake8

    - name: Analyse the Code with flake8
      run: flake8 --ignore=E501 .

